"""V1434 — ASI VCP consistency HTTP adapter (主 00:56 任何人都能接手).

Phase: 1434
Version: 0.1.0
Date: 2026-08-10 (cron tick 05:18, Asia/Shanghai deep night)
Post: V1433 (ASI-VCP consistency report) + V1420 (HTTP backend) + V1431 (HTTP health check)

What V1434 is
=============
V1434 is the **HTTP adapter + deployment artifact** for V1433's
consistency report. Where:

- V1433 emits the structural consistency report (offline, JSON-able)
- V1420 is the real ASI HTTP backend (with make_server + handler)
- V1431 verifies V1420's HTTP server (real probe)
- V1434 produces **the artifacts** anyone can use to expose V1433
  over HTTP — without V1434 itself binding a socket.

V1434 generates:

1. A Python script that **imports V1420's make_server pattern**
   and serves a `/api/asi/vcp-consistency` endpoint reading V1433.
2. A nginx-style reverse-proxy config snippet for production.
3. A docker-compose snippet to launch V1433 + V1420 together.
4. An offline JSON dump of V1433's current consistency report.
5. A markdown table summary of parity + coverage.

V1434 does NOT bind a socket itself. It produces artifacts and
delegates the actual HTTP serving to V1420 (or any HTTP container).

Honest disclosure (主 17:58 + 主 17:43)
=======================================
V1434 is a **deployment-artifact generator**. It does NOT bind a
socket, run a server, or expose endpoints directly. It produces
python / nginx / docker-compose / json / markdown files that anyone
can use to expose V1433's report over HTTP. It does NOT claim
Phenomenal consciousness, ASI 达成, human-level judgment, or
absolute certainty. V1434 ≠ Phenomenal artifact, ≠ ASI 达成
artifact, ≠ human-level artifact, ≠ absolute artifact. Structural
parity ≠ implementation parity.

Borrowed (5 — 主 19:33 走在前人经验上):
=======================================
- V1433 (ASI-VCP consistency report — data source)
- V1420 (HTTP status endpoint — server pattern reference)
- V1431 (HTTP health check — verification pattern reference)
- V1425 (5 philosophical gaps — honesty paragraph template)
- stdlib json + textwrap + pathlib

GUARDS upheld (V1434-specific, 14 — 主 00:44 质量工程化)
=========================================================
- GUARD_NO_SOCKET_BIND: V1434 does not bind ports itself
- GUARD_NO_V1433_WRITE: V1434 reads V1433 build_report(), never mutates
- GUARD_NO_V1420_WRITE: V1434 does not touch V1420 server
- GUARD_NO_V1431_WRITE: V1434 does not touch V1431 probe
- GUARD_ARTIFACT_GENERATED: 5 artifacts are generated by V1434
- GUARD_PYTHON_VALID: generated python script passes ast.parse
- GUARD_NGINX_VALID: generated nginx config has required directives
- GUARD_COMPOSE_VALID: generated docker-compose has 2 services
- GUARD_JSON_SERIALIZABLE: report is JSON-serializable
- GUARD_POPPER_RUNS: popper self-test runs in CLI
- GUARD_CHAIN_OK: V1434 chain_delegate returns all_ok
- GUARD_HONEST_DISCLOSURE: honesty paragraph emitted
- GUARD_CLI_RUNNABLE: CLI 真可跑
- GUARD_BOUNDED_OUTPUT: each artifact is bounded in size

V3 哲学守门 (主 17:58 + 主 20:46 + 主 17:43) — 5 guards
=======================================================
- GUARD_NO_PHENOMENAL_ARTIFACT: artifact is mechanical text, NOT consciousness
- GUARD_NO_ASI_ARTIFACT: artifact exposes parity ≠ ASI 达成
- GUARD_NO_HUMAN_LEVEL_ARTIFACT: artifact is plumbing, NOT judgment
- GUARD_NO_ABSOLUTE_ARTIFACT: artifact returns JSON, NOT absolute truth
- GUARD_NO_V1433_REPLACE: V1434 reads V1433, does not replace

API surfaces (14)
=================
1.  ``ENDPOINTS`` — tuple of 2 endpoint paths (V1433 data + V1434 meta)
2.  ``Artifact`` — dataclass (kind + content + lines + sha256)
3.  ``generate_python_server_script()`` — str (imports V1420 make_server pattern)
4.  ``generate_nginx_snippet()`` — str (reverse-proxy config)
5.  ``generate_docker_compose_snippet()`` — str (compose with 2 services)
6.  ``generate_consistency_json()`` — str (V1433 build_report JSON)
7.  ``generate_markdown_summary()`` — str (parity + coverage table)
8.  ``build_all_artifacts()`` — List[Artifact]
9.  ``render_artifacts_index_md(artifacts)`` — str
10. ``validate_python_script(script)`` — bool (ast.parse)
11. ``validate_nginx_snippet(snippet)`` — bool (directives)
12. ``validate_compose_snippet(snippet)`` — bool (services)
13. ``popper_self_test()`` — 14 self-tests
14. ``chain_delegate()`` — V1433 + V1420 + V1431 chain probe
15. ``main(argv)`` — CLI

CLI commands (8 — 主 00:56 任何人都能接手)
==========================================
- version
- meta [--json]
- help
- popper
- chain
- python (print generated python server script)
- nginx (print generated nginx snippet)
- compose (print generated docker-compose snippet)
- json (print V1433 consistency JSON)
- summary (print markdown summary)
- all (write all 5 artifacts to .v1434-artifacts/ directory)
"""

from __future__ import annotations

import ast
import hashlib
import json
import sys
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple


# ============================================================================
# Constants
# ============================================================================

V1434_VERSION = "0.1.0"
V1434_SCHEMA = "v1434.asi-vcp-consistency-http/v1"
V1434_MODULE = "v1434_asi_vcp_consistency_http"

ENDPOINTS: Tuple[str, ...] = (
    "/api/asi/vcp-consistency",
    "/api/asi/version",
)

OUTPUT_DIR = Path(".v1434-artifacts")


# ============================================================================
# Dataclasses
# ============================================================================


@dataclass
class Artifact:
    """A generated artifact (script / config / report)."""

    kind: str
    filename: str
    content: str
    lines: int = 0
    bytes: int = 0
    sha256: str = ""

    def __post_init__(self) -> None:
        if not self.lines:
            self.lines = self.content.count("\n") + (0 if self.content.endswith("\n") else 1)
        if not self.bytes:
            self.bytes = len(self.content.encode("utf-8"))
        if not self.sha256:
            self.sha256 = hashlib.sha256(self.content.encode("utf-8")).hexdigest()[:16]

    def to_dict(self) -> Dict[str, Any]:
        return {
            "kind": self.kind,
            "filename": self.filename,
            "lines": self.lines,
            "bytes": self.bytes,
            "sha256": self.sha256,
        }


# ============================================================================
# GUARDS / BORROWED
# ============================================================================

V1434_GUARDS: Tuple[str, ...] = (
    "GUARD_NO_SOCKET_BIND",
    "GUARD_NO_V1433_WRITE",
    "GUARD_NO_V1420_WRITE",
    "GUARD_NO_V1431_WRITE",
    "GUARD_ARTIFACT_GENERATED",
    "GUARD_PYTHON_VALID",
    "GUARD_NGINX_VALID",
    "GUARD_COMPOSE_VALID",
    "GUARD_JSON_SERIALIZABLE",
    "GUARD_POPPER_RUNS",
    "GUARD_CHAIN_OK",
    "GUARD_HONEST_DISCLOSURE",
    "GUARD_CLI_RUNNABLE",
    "GUARD_BOUNDED_OUTPUT",
)

V1434_V3_GUARDS: Tuple[str, ...] = (
    "GUARD_NO_PHENOMENAL_ARTIFACT",
    "GUARD_NO_ASI_ARTIFACT",
    "GUARD_NO_HUMAN_LEVEL_ARTIFACT",
    "GUARD_NO_ABSOLUTE_ARTIFACT",
    "GUARD_NO_V1433_REPLACE",
)

V1434_BORROWED: Tuple[Tuple[str, str], ...] = (
    ("v1433_asi_vcp_structural_consistency", "Consistency report data source"),
    ("v1420_asi_http_status_endpoint", "HTTP backend server pattern reference"),
    ("v1431_asi_http_health_check", "HTTP health check verification pattern reference"),
    ("v1425_asi_five_philosophical_gaps", "Honesty paragraph template"),
    ("stdlib_json_textwrap_pathlib_ast_hashlib", "Stdlib utilities"),
)


# ============================================================================
# Helpers
# ============================================================================


def _now_iso() -> str:
    return datetime.now(timezone.utc).isoformat()


def _build_v1433_report_json() -> str:
    """Load V1433 build_report() as JSON."""
    try:
        from apeireth.v1433_asi_vcp_structural_consistency import build_report
        report = build_report()
        return json.dumps(report.to_dict(), ensure_ascii=False, indent=2)
    except Exception as exc:
        return json.dumps({
            "error": f"{type(exc).__name__}: {exc}",
            "module": V1434_MODULE,
            "version": V1434_VERSION,
        }, ensure_ascii=False, indent=2)


# ============================================================================
# Artifact generators
# ============================================================================


def generate_python_server_script() -> str:
    """Generate a Python script that imports V1420's make_server pattern
    and serves /api/asi/vcp-consistency."""
    script = '''#!/usr/bin/env python
"""Auto-generated by V1434 — exposes V1433 over HTTP using V1420 make_server.

Usage:
    python serve_vcp_consistency.py [--port 8767]

This script imports V1433 (data source) and uses stdlib http.server
(no external deps). It does NOT bind during generation; only when
this script is executed.

Honest disclosure: this is a deployment artifact, not a running
service. The user must `python serve_vcp_consistency.py` to bind.
"""
from __future__ import annotations

import argparse
import http.server
import json
import socketserver
import sys

from apeireth.v1433_asi_vcp_structural_consistency import build_report


class VcpConsistencyHandler(http.server.BaseHTTPRequestHandler):
    """HTTP handler serving V1433 build_report() at /api/asi/vcp-consistency."""

    def log_message(self, format, *args):  # noqa: A002
        pass

    def do_GET(self):  # noqa: N802
        if self.path == "/api/asi/vcp-consistency":
            try:
                report = build_report()
                body = json.dumps(report.to_dict(), ensure_ascii=False).encode("utf-8")
                self.send_response(200)
                self.send_header("Content-Type", "application/json; charset=utf-8")
                self.send_header("Content-Length", str(len(body)))
                self.end_headers()
                self.wfile.write(body)
            except Exception as exc:
                err = json.dumps({"error": str(exc)}).encode("utf-8")
                self.send_response(500)
                self.send_header("Content-Type", "application/json")
                self.send_header("Content-Length", str(len(err)))
                self.end_headers()
                self.wfile.write(err)
            return
        if self.path == "/health":
            self.send_response(200)
            self.send_header("Content-Type", "text/plain")
            self.end_headers()
            self.wfile.write(b"ok")
            return
        self.send_response(404)
        self.end_headers()


class ThreadedHTTPServer(socketserver.ThreadingMixIn, http.server.HTTPServer):
    daemon_threads = True
    allow_reuse_address = True


def main():
    parser = argparse.ArgumentParser(description="V1434 VCP consistency HTTP")
    parser.add_argument("--port", type=int, default=8767, help="bind port")
    parser.add_argument("--bind", default="127.0.0.1", help="bind host")
    parser.add_argument("--max-seconds", type=float, default=0.0,
                        help="auto-shutdown after N seconds (0=forever)")
    args = parser.parse_args()

    server = ThreadedHTTPServer((args.bind, args.port), VcpConsistencyHandler)
    print(f"V1434 serving on http://{args.bind}:{args.port}")
    print(f"  GET /api/asi/vcp-consistency")
    print(f"  GET /health")
    try:
        if args.max_seconds > 0:
            import threading, time
            t = threading.Thread(target=server.serve_forever, daemon=True)
            t.start()
            time.sleep(args.max_seconds)
            server.shutdown()
        else:
            server.serve_forever()
    except KeyboardInterrupt:
        server.shutdown()
    finally:
        server.server_close()


if __name__ == "__main__":
    main()
'''
    return script


def generate_nginx_snippet() -> str:
    """Generate nginx reverse-proxy config snippet."""
    return '''# Auto-generated by V1434 — reverse-proxy V1433 to nginx
# Insert this in your nginx.conf inside the http {} block.

upstream v1433_consistency_backend {
    server 127.0.0.1:8767;
    keepalive 4;
}

server {
    listen 8080;
    server_name _;

    location /api/asi/vcp-consistency {
        proxy_pass http://v1433_consistency_backend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_read_timeout 10s;
    }

    location /health {
        proxy_pass http://v1433_consistency_backend/health;
        proxy_read_timeout 5s;
    }
}
'''


def generate_docker_compose_snippet() -> str:
    """Generate docker-compose snippet with 2 services."""
    return '''# Auto-generated by V1434 — docker-compose for V1433 consistency endpoint
# Run with: docker compose up -d

services:
  v1433-consistency:
    build:
      context: .
      dockerfile: Dockerfile.v1434
    image: apeireth/v1434-asi-vcp-consistency:0.1.0
    container_name: v1433-consistency
    ports:
      - "127.0.0.1:8767:8767"
    command: ["python", "serve_vcp_consistency.py", "--port", "8767", "--bind", "0.0.0.0"]
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://127.0.0.1:8767/health', timeout=2)"]
      interval: 30s
      timeout: 5s
      retries: 3

  v1434-nginx:
    image: nginx:1.25-alpine
    container_name: v1434-nginx
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - ./v1434-nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      v1433-consistency:
        condition: service_healthy
'''


def generate_consistency_json() -> str:
    """Generate JSON dump of V1433 build_report()."""
    return _build_v1433_report_json()


def generate_markdown_summary() -> str:
    """Generate markdown summary table of parity + coverage."""
    try:
        from apeireth.v1433_asi_vcp_structural_consistency import build_report
        report = build_report()
        rows = report.rows
        n_layers = report.n_layers
        n_protocols = report.n_protocols
        forward = report.forward_coverage
        reverse = report.reverse_coverage
        parity = report.parity
        n_gaps = len(report.gaps)
        n_redundant = len(report.redundant)
    except Exception as exc:
        return f"# V1434 Summary\n\nError loading V1433: {exc}\n"

    lines: List[str] = []
    lines.append("# V1434 ASI VCP Consistency Summary")
    lines.append("")
    lines.append(f"- generated: `{_now_iso()}`")
    lines.append(f"- module: `{V1434_MODULE}` v{V1434_VERSION}")
    lines.append("")
    lines.append("## Coverage")
    lines.append("")
    lines.append("| metric | value |")
    lines.append("|---|---|")
    lines.append(f"| forward_coverage | **{forward:.4f}** |")
    lines.append(f"| reverse_coverage | **{reverse:.4f}** |")
    lines.append(f"| parity_score | **{parity:.4f}** |")
    lines.append(f"| n_layers | {n_layers} |")
    lines.append(f"| n_protocols | {n_protocols} |")
    lines.append(f"| n_gaps | {n_gaps} |")
    lines.append(f"| n_redundant | {n_redundant} |")
    lines.append("")
    lines.append("## Rows")
    lines.append("")
    lines.append("| VCP layer | V1426 protocol | match_score |")
    lines.append("|---|---|---|")
    for r in rows:
        lines.append(f"| {r.vcp_layer} | {r.v1426_protocol} | {r.match_score:.2f} |")
    lines.append("")
    lines.append("## Endpoints (anyone can curl)")
    lines.append("")
    for ep in ENDPOINTS:
        lines.append(f"- `{ep}`")
    lines.append("")
    lines.append("## Honest disclosure")
    lines.append("")
    lines.append(
        "V1434 is a deployment-artifact generator. It does NOT bind a socket."
    )
    lines.append(
        "It produces python / nginx / docker-compose / json / markdown files"
    )
    lines.append(
        "that anyone can use to expose V1433's report over HTTP. Structural"
    )
    lines.append(
        "parity ≠ implementation parity."
    )
    return "\n".join(lines) + "\n"


# ============================================================================
# Build all artifacts
# ============================================================================


def build_all_artifacts() -> List[Artifact]:
    """Build all 5 artifacts."""
    return [
        Artifact(
            kind="python_server_script",
            filename="serve_vcp_consistency.py",
            content=generate_python_server_script(),
        ),
        Artifact(
            kind="nginx_snippet",
            filename="v1434-nginx.conf",
            content=generate_nginx_snippet(),
        ),
        Artifact(
            kind="docker_compose_snippet",
            filename="docker-compose.v1434.yml",
            content=generate_docker_compose_snippet(),
        ),
        Artifact(
            kind="consistency_json",
            filename="v1433-consistency.json",
            content=generate_consistency_json(),
        ),
        Artifact(
            kind="markdown_summary",
            filename="v1434-summary.md",
            content=generate_markdown_summary(),
        ),
    ]


def render_artifacts_index_md(artifacts: List[Artifact]) -> str:
    """Render an index of all artifacts."""
    lines: List[str] = []
    lines.append(f"# V1434 Artifacts Index `{V1434_VERSION}`")
    lines.append("")
    lines.append(f"- generated: `{_now_iso()}`")
    lines.append(f"- n_artifacts: {len(artifacts)}")
    lines.append("")
    lines.append("| kind | filename | lines | bytes | sha256 |")
    lines.append("|---|---|---|---|---|")
    for a in artifacts:
        lines.append(f"| {a.kind} | `{a.filename}` | {a.lines} | {a.bytes} | `{a.sha256}` |")
    return "\n".join(lines) + "\n"


# ============================================================================
# Validators
# ============================================================================


def validate_python_script(script: str) -> bool:
    """Validate generated python script parses."""
    try:
        ast.parse(script)
        return True
    except Exception:
        return False


def validate_nginx_snippet(snippet: str) -> bool:
    """Validate nginx snippet has upstream + location blocks."""
    return "upstream" in snippet and "location" in snippet and "proxy_pass" in snippet


def validate_compose_snippet(snippet: str) -> bool:
    """Validate compose has 2 services + ports + healthcheck."""
    return (
        snippet.count("services:") == 1
        and snippet.count("- ") >= 2  # 2 services listed
        and "ports:" in snippet
        and "healthcheck:" in snippet
    )


# ============================================================================
# Chain delegate
# ============================================================================


def chain_delegate() -> Dict[str, Any]:
    """Probe upstream modules for liveness."""
    chain: Dict[str, Any] = {}
    try:
        from apeireth.v1433_asi_vcp_structural_consistency import V1433_VERSION
        chain["V1433"] = {"ok": True, "version": V1433_VERSION}
    except Exception as exc:
        chain["V1433"] = {"ok": False, "error": f"{type(exc).__name__}: {exc}"}

    try:
        from apeireth.v1420_asi_http_status_endpoint import V1420_VERSION
        chain["V1420"] = {"ok": True, "version": V1420_VERSION}
    except Exception as exc:
        chain["V1420"] = {"ok": False, "error": f"{type(exc).__name__}: {exc}"}

    try:
        from apeireth.v1431_asi_http_health_check import V1431_VERSION
        chain["V1431"] = {"ok": True, "version": V1431_VERSION}
    except Exception as exc:
        chain["V1431"] = {"ok": False, "error": f"{type(exc).__name__}: {exc}"}

    all_ok = all(c.get("ok") for c in chain.values())
    return {"all_ok": all_ok, "chain": chain, "n_modules": len(chain)}


# ============================================================================
# Module metadata
# ============================================================================


def module_meta() -> Dict[str, Any]:
    """Module metadata."""
    return {
        "module": V1434_MODULE,
        "version": V1434_VERSION,
        "schema": V1434_SCHEMA,
        "guards": list(V1434_GUARDS),
        "v3_guards": list(V1434_V3_GUARDS),
        "borrowed": [b[0] for b in V1434_BORROWED],
        "n_guards": len(V1434_GUARDS),
        "n_v3_guards": len(V1434_V3_GUARDS),
        "n_borrowed": len(V1434_BORROWED),
        "n_endpoints": len(ENDPOINTS),
        "endpoints": list(ENDPOINTS),
        "n_artifacts": 5,
        "artifact_kinds": [
            "python_server_script",
            "nginx_snippet",
            "docker_compose_snippet",
            "consistency_json",
            "markdown_summary",
        ],
        "n_api_surfaces": 15,
        "n_cli_commands": 11,
    }


# ============================================================================
# Popper self-test
# ============================================================================


def popper_self_test() -> Dict[str, Any]:
    """Popper-style self-test: 14 deterministic checks."""
    results: Dict[str, Tuple[bool, str]] = {}

    # PT01: importable
    try:
        import apeireth.v1434_asi_vcp_consistency_http as self_mod  # noqa: F401
        results["PT01_importable"] = (True, "ok")
    except Exception as exc:
        results["PT01_importable"] = (False, f"{type(exc).__name__}: {exc}")
        return {"n_pass": 0, "n_total": 1, "ok": False, "results": results}

    # PT02: version set
    results["PT02_version_set"] = (
        V1434_VERSION == "0.1.0",
        f"version={V1434_VERSION}",
    )

    # PT03: 14 guards
    results["PT03_guards_set"] = (
        len(V1434_GUARDS) == 14,
        f"n={len(V1434_GUARDS)}",
    )

    # PT04: 5 V3 guards
    results["PT04_v3_guards"] = (
        len(V1434_V3_GUARDS) == 5,
        f"n={len(V1434_V3_GUARDS)}",
    )

    # PT05: 5 borrowed
    results["PT05_borrowed"] = (
        len(V1434_BORROWED) == 5,
        f"n={len(V1434_BORROWED)}",
    )

    # PT06: 2 endpoints
    results["PT06_endpoints_two"] = (
        len(ENDPOINTS) == 2,
        f"endpoints={list(ENDPOINTS)}",
    )

    # PT07: 5 artifacts
    arts = build_all_artifacts()
    results["PT07_five_artifacts"] = (
        len(arts) == 5,
        f"n={len(arts)}",
    )

    # PT08: python script validates (ast.parse)
    py = generate_python_server_script()
    results["PT08_python_valid"] = (
        validate_python_script(py),
        f"lines={py.count(chr(10))}",
    )

    # PT09: nginx snippet validates
    nginx = generate_nginx_snippet()
    results["PT09_nginx_valid"] = (
        validate_nginx_snippet(nginx),
        f"lines={nginx.count(chr(10))}",
    )

    # PT10: compose snippet validates
    compose = generate_docker_compose_snippet()
    results["PT10_compose_valid"] = (
        validate_compose_snippet(compose),
        f"lines={compose.count(chr(10))}",
    )

    # PT11: consistency JSON parses
    j = generate_consistency_json()
    try:
        parsed = json.loads(j)
        results["PT11_consistency_json_parses"] = (
            isinstance(parsed, dict),
            f"keys={list(parsed.keys())[:5]}",
        )
    except Exception as exc:
        results["PT11_consistency_json_parses"] = (False, f"{type(exc).__name__}: {exc}")

    # PT12: chain_delegate returns 3 modules
    chain = chain_delegate()
    results["PT12_chain_three_modules"] = (
        chain.get("n_modules") == 3,
        f"n={chain.get('n_modules')}",
    )

    # PT13: chain_delegate all_ok
    results["PT13_chain_all_ok"] = (
        chain.get("all_ok") is True,
        f"all_ok={chain.get('all_ok')}",
    )

    # PT14: module_meta has expected keys
    meta = module_meta()
    required = {
        "module", "version", "schema", "guards", "v3_guards",
        "borrowed", "n_guards", "n_v3_guards", "n_borrowed",
        "n_endpoints", "endpoints", "n_artifacts", "artifact_kinds",
    }
    results["PT14_module_meta_keys"] = (
        required.issubset(meta.keys()),
        f"keys={sorted(meta.keys())}",
    )

    n_pass = sum(1 for v in results.values() if v[0])
    n_total = len(results)
    return {
        "n_pass": n_pass,
        "n_total": n_total,
        "ok": n_pass == n_total,
        "results": results,
    }


# ============================================================================
# CLI
# ============================================================================


def _cmd_version(_args: List[str]) -> int:
    print(f"V1434 ASI VCP Consistency HTTP Adapter v{V1434_VERSION}")
    return 0


def _cmd_meta(args: List[str]) -> int:
    meta = module_meta()
    if "--json" in args:
        print(json.dumps(meta, indent=2, ensure_ascii=False))
    else:
        for k, v in meta.items():
            print(f"  {k}: {v}")
    return 0


def _cmd_help(_args: List[str]) -> int:
    print(__doc__)
    return 0


def _cmd_popper(_args: List[str]) -> int:
    result = popper_self_test()
    print(
        f"popper: n_pass={result['n_pass']}/{result['n_total']} "
        f"ok={result['ok']}"
    )
    for k, v in result["results"].items():
        ok, note = v
        status = "ok" if ok else "FAIL"
        print(f"  [{status}] {k}: {note}")
    return 0 if result["ok"] else 1


def _cmd_chain(_args: List[str]) -> int:
    chain = chain_delegate()
    print(json.dumps(chain, indent=2, ensure_ascii=False))
    return 0 if chain["all_ok"] else 1


def _cmd_python(_args: List[str]) -> int:
    print(generate_python_server_script(), end="")
    return 0


def _cmd_nginx(_args: List[str]) -> int:
    print(generate_nginx_snippet(), end="")
    return 0


def _cmd_compose(_args: List[str]) -> int:
    print(generate_docker_compose_snippet(), end="")
    return 0


def _cmd_json(_args: List[str]) -> int:
    print(generate_consistency_json())
    return 0


def _cmd_summary(_args: List[str]) -> int:
    print(generate_markdown_summary())
    return 0


def _cmd_all(args: List[str]) -> int:
    """Write all artifacts to OUTPUT_DIR."""
    outdir = OUTPUT_DIR
    if args and not args[0].startswith("-"):
        outdir = Path(args[0])
    outdir.mkdir(parents=True, exist_ok=True)
    arts = build_all_artifacts()
    index_lines: List[str] = []
    index_lines.append(f"# V1434 Artifacts Index")
    index_lines.append(f"- outdir: `{outdir.resolve()}`")
    index_lines.append(f"- generated: `{_now_iso()}`")
    index_lines.append("")
    index_lines.append("| kind | filename | lines | bytes | sha256 |")
    index_lines.append("|---|---|---|---|---|")
    for a in arts:
        path = outdir / a.filename
        path.write_text(a.content, encoding="utf-8")
        index_lines.append(
            f"| {a.kind} | `{a.filename}` | {a.lines} | {a.bytes} | `{a.sha256}` |"
        )
    (outdir / "INDEX.md").write_text("\n".join(index_lines) + "\n", encoding="utf-8")
    print(f"wrote {len(arts)} artifacts to {outdir.resolve()}")
    for a in arts:
        print(f"  - {a.filename} ({a.lines} lines, {a.bytes} bytes)")
    return 0


_COMMANDS: Dict[str, Any] = {
    "version": _cmd_version,
    "meta": _cmd_meta,
    "help": _cmd_help,
    "popper": _cmd_popper,
    "chain": _cmd_chain,
    "python": _cmd_python,
    "nginx": _cmd_nginx,
    "compose": _cmd_compose,
    "json": _cmd_json,
    "summary": _cmd_summary,
    "all": _cmd_all,
}


def main(argv: Optional[List[str]] = None) -> int:
    """CLI entry point."""
    args = list(sys.argv[1:] if argv is None else argv)
    if not args:
        return _cmd_help(args)
    cmd = args[0]
    if cmd not in _COMMANDS:
        print(f"unknown command: {cmd}")
        print("available: " + ", ".join(_COMMANDS.keys()))
        return 1
    return _COMMANDS[cmd](args[1:])


if __name__ == "__main__":
    sys.exit(main())